version = "Two"

blank_lines_upper_bound = 2
enum_discrim_align_threshold = 120
struct_field_align_threshold = 120
fn_params_layout = "Compressed"
format_code_in_doc_comments = true
format_macro_matchers = true
hard_tabs = true
hex_literal_case = "Upper"
match_block_trailing_comma = true
imports_granularity = "Module"
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
use_try_shorthand = true

ignore = []