[package]
name = "vulkan"
version = "0.1.0"
edition = "2021"
build = "bindgen/build.rs"

[build-dependencies]
reqwest = { version = "0.11.22", features = ["blocking", "rustls-tls"], default-features = false }
vk-parse = "0.12.0"