[package]
name = "vulkan"
version = "0.1.0"
edition = "2021"
build = "bindgen/build.rs"

[build-dependencies]
case_style = "0.2.1"
reqwest = { version = "0.11.22", features = ["blocking", "rustls-tls"], default-features = false }
vk-parse = "0.12.0"

[dependencies]
bitflags = "2.4.1"
